### ISSUE TITLE
Question: recommendation how to migrate from `yml` to `json` format

### ISSUE THREAD

**Issue by alexanderadam** [wout/rosetta#14]
Hello @wout, it's me again — a grateful user. :wink: 

Do you recommend any tooling / workflow if a project is currently using `yml` format and wants to migrate to `json`?

PS: Maybe you could activate the discussions tab for questions like that?
PPS: thank you for your work!

**Comment by wout** [comment]
Hi! Glad to hear you like Rosetta! 🙂️

For YAML to JSON conversions, I mostly use the [YamlToJson](https://packagecontrol.io/packages/YamlToJson) package for Sublime text. But similar tools probably exist for other editors as well.

A discussion tab is created. Thanks for the suggestion!

**Comment by wout** [comment]
> Okay, I'll search and try these tools then.

Sorry I can't provide you with something fancier. 😄️ It's not something that happens often to be honest.
