### ISSUE TITLE
Implement fallbacks

### ISSUE THREAD

**Issue by wout** [wout/rosetta#8]
Allow regional locales (e.g. `en-US` and `en-GB`) to provide a partial keyset and pull the missing keys from the base locale (`en`).

**Comment by alexanderadam** [comment]
Is it possible to work around this for now somehow?

**Comment by wout** [comment]
I'll have to look into it, but as it is right now, every set is evaluated individually. I haven't implemented it yet because I don't have the need for it. I was waiting for someone to request it, and here you are. 🤓️

I'll check and let you know.

**Comment by wout** [comment]
Okay, this isn't too hard to implement. At most, a few new methods. I'll try to squeeze it in this week.

**Comment by wout** [comment]
Haven't been able to get to it; something else came up. But it's high on my priority list.

**Comment by wout** [comment]
@alexanderadam
A basic version of this is now implemented in v0.11.0. I still need to update the docs, though.

It works by adding a `Rosetta::FallbackRules` annotation:

```crystal
@[Rosetta::AvailableLocales(:en, "en-US", :nl)]
@[Rosetta::FallbackRules({
  "en-US": "en",
})]
```

You can't add an array of fallbacks. If that's needed, I can implement that too. It just needs a bit more work.

Let me know how it goes! I may have overlooked something.

**Comment by wout** [comment]
I'm going to close this now. Let me know if you have any questions or suggestions.

**Comment by alexanderadam** [comment]
Nice, thank you so much! :heart_eyes: 
I'll check it out!
